config/routes.rb
Wispper::Application.routes.draw do
  # for niçe URL with locale as parameter. locale is not necesary and goes first to en than to de
  scope "(:locale)", locale: /es|de|en/ do
    authenticated :user do
        # Rails 4 users must specify the 'as' option to give it a unique name
        root :to => "feeds#index", :as => "authenticated_root"
      end
    resources :posts
    resources :feeds, :path => "feeds"
    get "feeds/all/:index_type" => "feeds#index", :as => "all_feeds_of_type"
    root :to => "home#index"
    get "feeds/:feed_id/posts/new" => "posts#new", :as => "new_post_for_feed"
    devise_for :users, :controllers => {:registrations => "registrations", :sign_in => "home"}
    resources :users
    post "evaluations/:id" => "evaluations#accept_post",  as: "accept_post"
    delete "evaluations/:id" => "evaluations#decline_post",  as: "decline_post"
    put "evaluations/:id" => "evaluations#pass_post",  as: "pass_post"
    get "search/" => "search#show", as: "search"
    put "feedlang/" => "users#set_feed_languages", as: "set_feed_languages"
    get "explain/trust" => "home#trust", as: "explain_trust"
    get "send/notifications/:id" => "feeds#send_stage_up_notification_email", as: "send_stage_up_notification_email"
  end
end

app/models/feed.rb
class Feed < ActiveRecord::Base
  has_paper_trail :ignore => [:last_activity, :contributor_count, :updated_at, :status, :stage]
  has_many :evaluations, :class_name => "Evaluation", :foreign_key => "feed_id"
  has_many :posts, :class_name => "Post", :foreign_key => "feed_id"
  
  cattr_accessor :stage_up
  
  validates :goal, length: { in: 10..160 }
  validates :rule1, length: { in: 10..160 }
  validates :rule2, length: { in: 10..160 }
  validates :rule3, length: { in: 0..160 }
  validates :rule4, length: { in: 0..160 }
  validates :rule5, length: { in: 0..160 }
  
  scope :all_active, -> {where(status: "active")}
  scope :all_free, -> {where(status: "free")}
  scope :all_contributed_feeds, -> (user_id){joins(:posts).where(posts:{creator_id: user_id}).distinct}
  
  # to show the user in the index view
  scope :all_feeds_user_needs_to_evaluate, -> (user_id){joins(:evaluations).where(evaluations:{status: "pending", user_id: user_id}).distinct(:feed)}
  
  # for the search controller
  scope :search, -> (query){where("goal LIKE ? OR rule1 LIKE ? OR rule2 LIKE ? OR rule3 LIKE ? OR rule4 LIKE ? OR rule5 LIKE ?", "%#{query}%", "%#{query}%", "%#{query}%", "%#{query}%", "%#{query}%", "%#{query}%")}
  
  
  # returns an array with all the user_ids of unique contributors depending on the past status of the feed
  def contributors(status = self.status)
    if status == "free"
      stati = ["active", "free", "in_evaluation"]
    elsif status == "active"
      stati = "active"
    end
    p = posts.where(status: stati).select(:creator_id).distinct
    c = []
    p.each do |post|
      # create an array of all contributor ids
      c.push (post.creator_id) 
    end
    c
  end
  
  # returns an array with all the data (name, email, lang) of unique contributors depending on the past status of the feed
  def contributor_data
    User.select(:id, :name, :email, :lang).where(id: contributors)
  end
  
   # returns the Stage based on status and contributors
  def check_stage(con = contributor_count)
    case 
    when con >= STAGE_0_1
      if self.status == "free"
        1
      else
        2
      end
    when con >= STAGE_2
      3
    when con >= STAGE_3
      4
    when con >= STAGE_4
      5
    else
      if self.status == "free"
        0
      else
        1
      end
    end
  end
  
  # checks if the contributor is new; takes the real contributor count (a fresh created "in_evaluation" post does not increase contributor count in active feeeds)
  # used at post creation (contributors only change on "free" feeds) and post evaluation (acceptance and rejection)
  def update_stats
    return_var = Hash.new
    if self.contributor_count != contributors.count
      self.contributor_count = contributors.count
      return_var[:contributor] = "changed"
    else
      return_var[:contributor] = "stayed"
    end
    actual_stage = check_stage(self.contributor_count)
    if self.stage != nil and actual_stage > self.stage   #Stage UP!!
      self.stage = actual_stage
      return_var[:stage] = "changed"
    else
      return_var[:stage] = "stayed"
    end
    self.last_activity = Time.now
    return_var[:activity] = "changed"
    self.save
    return_var
  end

  # This method updates the status of the feed if necessary from free to active; USED IN evaluations_controller
  def check_status_change_to_active
    c = posts.where(status: "active").select(:creator_id).distinct.size
    if c >= STAGE_0_1
      self.update(status: "active")
    end
  end

  def active_posts
    posts.where(status: "active")
  end
  

end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_filter :authenticate_user!
  # load_and_authorize_resource 
  before_action :set_feed, only: [:show, :update, :destroy]

  # GET /feeds
  # GET /feeds.json
  def index
    case params[:index_type]
    when "free"
      @feeds = Feed.all_free.where(lang: current_user.feedlang).order(contributor_count: :desc, last_activity: :desc).first(20)
    when "contributed"
      @feeds = Feed.all_contributed_feeds(current_user.id).order(contributor_count: :desc, last_activity: :desc).first(20)
    when "active"
      @feeds = Feed.all_active.where(lang: current_user.feedlang).order(contributor_count: :desc, last_activity: :desc).first(20)
    else
      @feeds = Feed.all.where(lang: current_user.feedlang).order(contributor_count: :desc, last_activity: :desc).first(20)
    end

    @created_feeds = Feed.where(creator_id: current_user.id)
    @feeds_to_evaluate = Feed.all_feeds_user_needs_to_evaluate(current_user.id)
    
    # is automatically set after first time
    # if params[:no_joyride] == "true"  #if user want to not see the joyride anymore
    #   key = "no_joyride_for_" + (current_user.id * 9 - 5).to_s
    #   unless cookies[key] == "true" #check if user is already in cookie
    #     cookies[key] = "true" #  Create or apend to cookie
    #   end
    # end
    # render stream: true
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
    # posts the user has to evaluate
    # @posts_to_evaluate = current_user.posts_to_be_evaluated_in_feed(params[:id])  FROM user model
    @posts_to_evaluate = Post.joins(:evaluations).where(evaluations:{status:"pending", user_id: current_user.id}).where(feed_id: params[:id]).order(created_at: :desc)
    # user's posts which are still in_evaluation to show in a list
    # @users_posts = current_user.own_posts_in_evaluation_and_feed(params[:id])
    @users_posts = Post.where(status: ["in_evaluation", "free"], creator_id: current_user.id, feed_id: params[:id]).order(created_at: :desc)
    # posts the user evaluated (accepted or declined or passed) but are still in_evaluation to show in a list
    @evaluated_posts = Post.joins(:evaluations).where(evaluations:{status: ["accepted", "declined", "passed"], user_id: current_user.id}).where(status: "in_evaluation", feed_id: params[:id]).eager_load(:evaluations).order(created_at: :desc)
    # for marking users evaluations
    eval = Evaluation.where(status: ['accepted', 'declined', "passed", 'too_late'], feed_id: params[:id], user_id: current_user.id).select(:status, :post_id)
    @evaluated_active_post = Hash.new
    eval.each do |e|
      @evaluated_active_post[e.post_id] = e.status
    end
    # all active posts (TO DO: check is eager_load is better for SQL server) with eager load of their creators (makes one big query instead of a query for each post)
    if @feed.status == "active"
      @posts = Post.where(status: "active", feed_id: params[:id]).order(created_at: :desc).eager_load(:creator)
    elsif @feed.status == "free"
      @posts = Post.where(status: ["free", "in_evaluation", "active"], feed_id: params[:id]).order(created_at: :desc).eager_load(:creator)
    end
    
    # render stream: true
  end

  # GET /feeds/new
  def new
    @feed_for_form = Feed.new(creator_id: current_user.id)
    @feed_for_form.lang = I18n.locale
  end

  # GET /feeds/1/edit
  def edit
    @feed_for_form = Feed.find(params[:id])
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(feed_params)
    # a freshly created feed is "free" like the posts in it; later it becomes "active" and the posts "in_evaluation" 
    @feed.status = "free"
    @feed.contributor_count = 0
    @feed.stage = 0
    @feed.last_activity = Time.now
    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: t('feed_create_success') }
        format.json { render action: 'show', status: :created, location: @feed }
      else
        format.html { render action: 'new' }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feeds/1
  # PATCH/PUT /feeds/1.json
  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feed
      @feed = Feed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feed_params
      params.require(:feed).permit(:goal, :rule1, :rule2, :rule3, :rule4, :rule5, :misc, :description, :lang, :anonymity, :status, :creator_id)
    end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_codex.html.haml
.codex
  .codex_why
    = t('codex_why')
  .codex_why_content  
    =feed.goal
  .codex_how
    = t('codex_how')
  .codex_how_content
    = t('how_start')
    = t(feed.lang)
    = t("and")
    - case feed.anonymity
    - when "all"
      = t("all_anonymous")
    - when "choice"
      = t("choice_anonymous")
    - when "nobody"
      = t("nobody_anonymous")
    = t('how_end')
  .codex_what= t('codex_what')
  .codex_what_content
    %ul.square
      - if feed.rule1 != ""
        %li= feed.rule1
      - if feed.rule2 != ""
        %li= feed.rule2
      - if feed.rule3 != ""
        %li= feed.rule3
      - if feed.rule4 != ""
        %li= feed.rule4
      - if feed.rule5 != ""
        %li= feed.rule5
  - if feed.misc != ""
    .codex_misc
      = t('codex_misc')
    .codex_misc_content
      %ul.square
        - feed.misc.split(",").each do |m|
          %li= m
  - if feed.description != ""
    .codex_description
      = t('codex_description')
    .codex_description_content
      = feed.description

app/views/feeds/_codex_short.html.haml
.codex
  .codex_why_content  
    %span.has-tip.tip-bottom.tip-left{class: "radius", "data-options" => "disable_for_touch:true", "data-tooltip" => "", title: t('codex_why')}= feed.goal
  
  .codex_how_content
    %span.has-tip.tip-bottom.tip-left{class: "radius", "data-options" => "disable_for_touch:true", "data-tooltip" => "", title: t('codex_how')}
      = t('how_start')
      = t(feed.lang)
      = t("and")
      - case feed.anonymity
      - when "all"
        = t("all_anonymous")
      - when "choice"
        = t("choice_anonymous")
      - when "nobody"
        = t("nobody_anonymous")
      = t('how_end')

  .codex_what_content
    %span.has-tip.tip-bottom.tip-left{class: "radius", "data-options" => "disable_for_touch:true", "data-tooltip" => "", title: t('codex_what')}
      %ul.square
        - if feed.rule1 != ""
          %li= feed.rule1
        - if feed.rule2 != ""
          %li= feed.rule2
        - if feed.rule3 != ""
          %li= feed.rule3
        - if feed.rule4 != ""
          %li= feed.rule4
        - if feed.rule5 != ""
          %li= feed.rule5
  
  - if feed.misc != ""
    .codex_misc_content
      %span.has-tip.tip-bottom.tip-left{class: "radius", "data-options" => "disable_for_touch:true", "data-tooltip" => "", title: t('codex_misc')}
        %ul.square
          - feed.misc.split(",").each do |m|
            %li= m

  - if feed.description != ""
    .codex_description_content
      %span.has-tip.tip-bottom.tip-left{class: "radius", "data-options" => "disable_for_touch:true", "data-tooltip" => "", title: t('codex_description')}= feed.description

app/views/feeds/_evaluate_post_box.haml
.row
  .large-12.columns.post_content
    = post_content(post.content)

.row
  .small-10.columns.small-centered
    %ul.button-group.radius.evaluation_button_list
      %li= link_to t("accept_eval"), accept_post_path(post.id), class: "button small accept_evaluation_button no-bottom-margin", method: :post
      %li= link_to t("decline_eval"), decline_post_path(post.id), class: "button small decline_evaluation_button no-bottom-margin", method: :delete
      %li= link_to t("pass_eval"), pass_post_path(post.id), class: "button small pass_evaluation_button no-bottom-margin", method: :put

app/views/feeds/_feed_box.html.haml
- if feed.status == "active"
  - status_class = "active_entry_color"   
- else 
  - status_class = "free_entry_color"
  
- if @created_feeds.include? feed  
  - status_class << " created_feed"

- if @feeds_to_evaluate.include? feed
  - status_class << " pending_feed"

.feed_box{class: status_class}
  .row
    .small-3.columns
      = image_tag("stage" + feed.stage.to_s + ".png", size: "80x80", :alt => t("feed_lvl0"))
      .label.top-margin.radius= feed.lang
      - if @feeds_to_evaluate.include? feed
        .label.top-margin.pending_evaluation.radius= feed.evaluations.where(user_id: current_user.id, status: "pending").length
    .small-9.columns.freed_box_title
      = link_to feed.goal, feed_path(feed)

app/views/feeds/_feed_stats.html.haml
.feed_stats
  .row
    .small-4.columns
      Con:
      = @feed.contributors.size
    .small-4.columns
      Pos:
      = @feed.active_posts.size
      &frasl;
      = @feed.posts.size
    .small-4.columns
      Ev:
      = Evaluation.not_pending_evaluations_of_feed(@feed.id).size
      &frasl;
      = Evaluation.all_evaluations_of_feed(@feed.id).size

app/views/feeds/_form.html.haml
= simple_form_for(@feed_for_form) do |f|
  = f.error_notification

  .form-inputs
    .new_feed_why
      = f.input :goal, :autofocus => true, placeholder: t("goal_placeholder"), label: t("goal_label")
    .new_feed_how
      = f.input :lang, collection: LANGUAGES_HASH.invert, :include_blank => false, label: t("lang_label")
      = f.input :anonymity, collection: {all: t("all_anonymous"), choice: t("choice_anonymous"), nobody: t("nobody_anonymous") }.invert, :include_blank => false, label: t("anonymity_feed_label")
    .new_feed_what
      = f.input :rule1, placeholder: t("needed_rule_placeholder"), label: t("rules_label")
      = f.input :rule2, placeholder: t("needed_rule_placeholder"), label: false
      = f.input :rule3, placeholder: t("rules_placeholder"), label: false
      = f.input :rule4, placeholder: t("rules_placeholder"), label: false
      = f.input :rule5, placeholder: t("rules_placeholder"), label: false
    .new_feed_rest
      = f.input :misc, placeholder: t("misc_placeholder"), label: t("misc_label")
      = f.input :description, placeholder: t("description_placeholder"), label: t("description_label")
      = f.hidden_field :creator_id

  .form-actions
    = f.button :submit, t("create_feed_button"), class: "button radius success", :data => { :confirm => t('sure_create_feed') }
    = link_to t("back_button"), feeds_path, class: "button radius alert"

app/views/feeds/_free_stats.html.haml
- if @feed.stage == 0
  .free_stats
    .row
      .small-3.columns
        = image_tag("stage0.png", size: "80x80", :alt => t("feed_lvl0"))
      .small-6.columns
        .row
          .small-12.columns.text-center
            = t("free_needs_contributors")
        .row
          .progress.small-12.success.radius
            .meter{:style => "width: " + ((@feed.contributors("free").size.to_f/STAGE_0_1.to_f)*100).to_i.to_s + "%"}
      .small-3.columns
        = image_tag("stage1.png", size: "80x80", :alt => t("feed_lvl1"))
- if @feed.stage == 1
  .free_stats
    .row
      .small-3.columns
        = image_tag("stage1.png", size: "80x80", :alt => t("feed_lvl1"))
      .small-6.columns
        .row
          .small-12.columns.text-center
            = t("free_needs_accepted_contributors")
        .row
          .progress.small-12.success.radius
            .meter{:style => "width: " + ((@feed.contributors("active").size.to_f/STAGE_0_1.to_f)*100).to_i.to_s + "%"}
      .small-3.columns
        = image_tag("stage2.png", size: "80x80", :alt => t("feed_lvl2"))

app/views/feeds/_new_feed_codex_short.haml
.codex
  .codex_why_content  
    %span.has-tip.tip-bottom.tip-left{class: "radius", "data-options" => "disable_for_touch:true", "data-tooltip" => "", title: t('codex_why')}= t("new_feed_why")

  .codex_how_content
    %span.has-tip.tip-bottom.tip-left{class: "radius", "data-options" => "disable_for_touch:true", "data-tooltip" => "", title: t('codex_how')}= t('new_feed_how')

  .codex_what_content
    %span.has-tip.tip-bottom.tip-left{class: "radius", "data-options" => "disable_for_touch:true", "data-tooltip" => "", title: t('codex_what')}
      %ul.square
        %li= t('new_feed_what1')
        %li= t('new_feed_what2')
        %li= t('new_feed_what3')

  .codex_misc_content
    %span.has-tip.tip-bottom.tip-left{class: "radius", "data-options" => "disable_for_touch:true", "data-tooltip" => "", title: t('codex_misc')}= t("new_feed_misc")

  .codex_description_content
    %span.has-tip.tip-bottom.tip-left{class: "radius", "data-options" => "disable_for_touch:true", "data-tooltip" => "", title: t('codex_description')}= t("new_feed_description")

app/views/feeds/_post_box.haml
.row
  .large-12.columns.post_content
    = post_content(post.content)
.row
  .small-5.columns
    .post_footer.post_creator
      = post.creator.name if post.anonymity == "visible" and post.status == "active"
      = t("post_is_free") if post.status == "free"
  .small-3.columns
    .post_footer
      -unless @evaluated_active_post[post.id] == nil
        %span.has-tip.tip-bottom{class: "radius", "data-options" => "disable_for_touch:true", "data-tooltip" => "", title: t('user_tooltip_' + @evaluated_active_post[post.id].to_s)}
          = t("user_eval_" + @evaluated_active_post[post.id].to_s)
  .small-4.columns
    .post_footer.post_datetime
      = l(post.created_at.localtime, format: :long)

app/views/feeds/_post_box_bar.html.haml
.row
  .small-12.columns
    .post_content
      = post_content(post.content)
.row
  .small-10.small-offset-1.columns.end
    .progress.radius.no-bottom-margin
      .meter{:style => "width: " + ((post.all_evaluated.count.to_f/post.real_evaluations.count.to_f)*100).to_i.to_s + "%"}
.row
  .small-5.columns
    .post_footer.post_creator
      = t("post_in_evaluation")
  .small-3.columns
    .post_footer
      -unless @evaluated_active_post[post.id] == nil
        %span.has-tip.tip-bottom{class: "radius", "data-options" => "disable_for_touch:true", "data-tooltip" => "", title: t('user_tooltip_' + @evaluated_active_post[post.id].to_s)}
          = t("user_eval_" + @evaluated_active_post[post.id].to_s) 
  .small-3.columns
    .post_footer.post_datetime
      = l(post.created_at.localtime, format: :long)
    
    
   

app/views/feeds/_waiting_posts.html.haml
- if !@evaluated_posts.empty?
  %p
    %h5= t('posts_user_evaluated')
    - @evaluated_posts.each do |ep|
      .evaluated_posts
        .evaluated_post_content= post_content(ep.content )
        -if ep.evaluations.first.status == "accepted"
          .evaluated_post_status.accepted
            .row
              .small-4.columns
                = t("user_accepted")
              .small-8.columns
                .progress.radius.no-bottom-margin.small
                  .meter{:style => "width: " + ((ep.all_evaluated.count.to_f/ep.real_evaluations.count.to_f)*100).to_i.to_s + "%"}
        -elsif ep.evaluations.first.status == "declined"
          .evaluated_post_status.declined
            .row
              .small-4.columns
                = t("user_declined")
              .small-8.columns
                .progress.radius.no-bottom-margin
                  .meter{:style => "width: " + ((ep.all_evaluated.count.to_f/ep.real_evaluations.count.to_f)*100).to_i.to_s + "%"}
        -elsif ep.evaluations.first.status == "passed"
          .evaluated_post_status.passed
            .row
              .small-4.columns
                = t("user_passed_on")
              .small-8.columns
                .progress.radius.no-bottom-margin
                  .meter{:style => "width: " + ((ep.all_evaluated.count.to_f/ep.real_evaluations.count.to_f)*100).to_i.to_s + "%"}
- if !@users_posts.empty?
  %p
    %h5= t('users_posts_not_active')
    - @users_posts.each do |post|
      .waiting_posts
        = render "post_box", post: post if post.status == "free"
        = render "post_box_bar", post: post if post.status == "in_evaluation"

app/views/feeds/edit.html.haml
%h1 Editing feed

= render 'form'

= link_to 'Show', @feed
\|
= link_to t("back_button"), feeds_path

app/views/feeds/index.html.haml
.row.top-margin
  .small-6.medium-4.columns.freed_header#jr_freed_header
    - case params[:index_type]
    - when "free"
      = t("free_feed_list")
    - when "contributed"
      = t("contributed_feed_list")
    - when "active"
      = t("active_feed_list")
    - else
      = t("all_feeds_list")
    - string = t("in") + " "
  .small-6.medium-4.columns.freedlang_header
    - if current_user.feedlang.kind_of?(Array)
      - current_user.feedlang.each_with_index do |l,i|
        - string << LANGUAGES_HASH[l.to_sym].humanize
        - string << ", " if i < current_user.feedlang.size - 2 
        - string << " " + t("and") + " " if i == current_user.feedlang.size - 2
    - else
      - string << LANGUAGES_HASH[current_user.feedlang.to_sym].humanize
    %span.has-tip.tip-bottom{class: "radius", "data-options" => "disable_for_touch:true", "data-tooltip" => "", title: t('change_feed_lang')}= link_to string, edit_user_registration_path, id: "jr_change_lang"
  .small-12.medium-4.columns.end
    = link_to t("new_feed"), new_feed_path(), class: "button success  radius nav_button", id: "jr_create_feed"
   



- @feeds.each_slice(3) do |tripplets|
  .row
    - tripplets.each_with_index do |feed, i|
      .large-4.large-offset-0.medium-offset-2.medium-8.columns{class: ("end" if i == tripplets.size-1)}  
        .freed_list
          = render "feed_box", feed: feed
  

%ol.joyride-list{"data-joyride" => ""}
  - unless cookies["no_joyride_for_" + (current_user.id * 9 - 6).to_s] == "true"
    %li{"data-id" => "jr_start_joyride", "data-button" => t("jr_start_tour")}
      %h4= t('jr_help_button_title')
      %p= t('jr_help_button_text')
  %li{"data-button" => t("jr_start_tour")}
    %h4= t('jr_welcome_page_title')
    %p= t('jr_welcome_page_text')
  %li{"data-id" => "jr_freed_header", "data-button" => t("jr_next")}
    %h4= t('jr_feed_header_title')
    %p= t('jr_feed_header_text')
  %li{"data-id" => "jr_change_lang", "data-button" => t("jr_next")}
    %h4= t('jr_feed_change_lang_title')
    %p= t('jr_feed_change_lang_text')
  %li{"data-id" => "jr_create_feed", "data-button" => t("jr_next")}
    %h4= t('jr_feed_create_feed_title')
    %p= t('jr_feed_create_feed_text')
  %li{"data-id" => "jr_trust_link", "data-button" => t("jr_next")}
    %h4= t('jr_trust_title')
    %p= t('jr_trust_text')
  %li{"data-id" => "jr_profile_link", "data-button" => t("jr_next")}
    %h4= t('jr_profile_title')
    %p= t('jr_profile_text')
  %li{"data-button" => t("jr_to_posts")}
    %h4= t('jr_feed_index_title')
    %p= simple_format(t('jr_feed_index_text'))
 
    

app/views/feeds/new.html.haml
.row
  .large-12.columns.top-margin
    %h3= t('new_feed')
.row
  .large-5.large-push-7.columns
    = render "new_feed_codex_short"
  .large-7.large-pull-5.columns
    = render 'form'