config/routes.rb
Wispper::Application.routes.draw do
  # for niçe URL with locale as parameter. locale is not necesary and goes first to en than to de
  scope "(:locale)", locale: /es|de|en/ do
    authenticated :user do
        # Rails 4 users must specify the 'as' option to give it a unique name
        root :to => "feeds#index", :as => "authenticated_root"
      end
    resources :posts
    resources :feeds, :path => "feeds"
    get "feeds/all/:index_type" => "feeds#index", :as => "all_feeds_of_type"
    root :to => "home#index"
    get "feeds/:feed_id/posts/new" => "posts#new", :as => "new_post_for_feed"
    devise_for :users, :controllers => {:registrations => "registrations", :sign_in => "home"}
    resources :users
    post "evaluations/:id" => "evaluations#accept_post",  as: "accept_post"
    delete "evaluations/:id" => "evaluations#decline_post",  as: "decline_post"
    put "evaluations/:id" => "evaluations#pass_post",  as: "pass_post"
    get "search/" => "search#show", as: "search"
    put "feedlang/" => "users#set_feed_languages", as: "set_feed_languages"
    get "explain/trust" => "home#trust", as: "explain_trust"
    get "send/notifications/:id" => "feeds#send_stage_up_notification_email", as: "send_stage_up_notification_email"
  end
end

app/views/layouts/TO DO code.haml
- if user_signed_in?
  %li.divider
  %li.has-dropdown.not-click
    %a{href: "#"} My...
    %ul.dropdown
      %li
        %a{href: "#"} ... freeds
      %li
        %a{href: "#"} ... posts
      %li
        %a{href: "#"} ... curations
      %li
        %a{href: "#"} ... contributions
        %li= link_to "profile", user_path(current_user.id)

app/views/layouts/_footer.html.haml
.row
  .large-12.columns
    .footer
      %ul.inline-list
        %li
          %a#jr_start_joyride{href: "#"}= t("jr_page_tour") if current_user
        %li= link_to "Impressum", "http://www.ovantu.com"
        %li= link_to "Disclaimer", "http://www.ovantu.com"
        %li= link_to "Contact", "http://www.ovantu.com"
        %li= link_to "ovantu.com", "http://www.ovantu.com"      
      

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Zurb Foundation
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:id => "hide", :class => "alert-box radius #{name == :notice ? "success" : "alert"}", "data-alert" => ""}
      = content_tag :div, msg
      %a.close{:href => "#"} &times;

app/views/layouts/_navigation.html.haml
-# navigation styled for Zurb Foundation 5
-# the syntax for data-topbar may need to change for Zurb Foundation 5
%nav.top-bar
  %ul.title-area
    %li.name
      = link_to 'Home', root_path
  .top-bar-section.right
    %ul
      %li
        = link_to t('feeds'), feeds_path
        = render 'layouts/navigation_links'


%nav.tab-bar.show-for-small
  %a.left-off-canvas-toggle
    Menu
  <!-- Off Canvas Menu -->
  %aside.left-off-canvas-menu
    <!-- whatever you want goes here -->
    %ul.off-canvas-list
      %li
        %a href="#">Lucy
      %li
        %a href="#">Luis


  <!-- close the off-canvas menu -->
  %a.exit-off-canvas

app/views/layouts/_navigation_links.html.erb
NOT IN USE

<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Login', new_user_session_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
<% else %>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.has_role? :admin %>
    <li><%= link_to 'Admin', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/_off_canvas.html.haml
%nav.tab-bar.show-for-small
  %section.left-small
    %a.left-off-canvas-toggle.menu-icon
      %span
  %section.middle.tab-bar-section
    %h1.title= t("page_title")
  -if feed
    %section.right-small
      %a.right-off-canvas-toggle.menu-icon
        %span
    
%aside.left-off-canvas-menu
  %ul.off-canvas-list
    %li
      %label= t("search_label")
    %li
      = form_tag search_path, :method => 'get' do
        .row.collapse
          .small-9.columns
            = text_field_tag :query, params[:query]
          .small-3.columns    
            = submit_tag t("search_button"), :name => nil, class: "button radius postfix"
    %li
      %label= t("feeds_drop")
    %li= link_to t("new_feed"), new_feed_path()
    %li= link_to t("all_feeds_list"), feeds_path()      
    %li= link_to t("contributed_feed_list"), all_feeds_of_type_path(index_type: "contributed")
    %li= link_to t("active_feed_list"), all_feeds_of_type_path(index_type: "active")
    %li= link_to t("free_feed_list"), all_feeds_of_type_path(index_type: "free")

    - if user_signed_in?
      %li
        %label= current_user.name
      %li
        = link_to t("profile_link"), user_path(current_user.id)
      %li
        = link_to t('edit_account_link'), edit_user_registration_path
      %li
        = link_to t('logout_link'), destroy_user_session_path, :method=>'delete'



-# The right off-canvas for the codex

-if feed
  %aside.right-off-canvas-menu
    %ul.off-canvas-list
      %li
        %label= t('codex')
      = render "codex_short", feed: @feed
      - if @evaluated_posts.size > 0
        %li
          %label= t("evaluated_posts_list") 
          - @evaluated_posts.each do |ep|
            %li
              .evaluated_post_content= ep.content 
              -if ep.evaluations.first.status == "accepted"
                .evaluated_post_status.accepted
                  .row
                    .small-4.columns
                      = t("user_accepted")
                    .small-8.columns
                      .progress.radius.no-bottom-margin.small
                        .meter{:style => "width: " + ((ep.all_evaluated.count.to_f/ep.real_evaluations.count.to_f)*100).to_i.to_s + "%"}
              -elsif ep.evaluations.first.status == "declined"
                .evaluated_post_status.declined
                  .row
                    .small-4.columns
                      = t("user_declined")
                    .small-8.columns
                      .progress.radius.no-bottom-margin
                        .meter{:style => "width: " + ((ep.all_evaluated.count.to_f/ep.real_evaluations.count.to_f)*100).to_i.to_s + "%"}
              -elsif ep.evaluations.first.status == "passed"
                .evaluated_post_status.passed
                  .row
                    .small-4.columns
                      = t("user_passed_on")
                    .small-8.columns
                      .progress.radius.no-bottom-margin
                        .meter{:style => "width: " + ((ep.all_evaluated.count.to_f/ep.real_evaluations.count.to_f)*100).to_i.to_s + "%"}
      - if @users_posts.size > 0
        %li
          %label= t("waiting_posts_list")
        - @users_posts.each do |ep|
          %li
            .waiting_posts= render "post_box", post: ep

%a.exit-off-canvas{href: "#"}

app/views/layouts/_top_bar.html.haml
.contain-to-grid.sticky.fixed{"data-options" => "sticky_on: large"}
  %nav.hide-for-small.top-bar{"data-topbar" => ""}
    %ul.title-area
      %li.name
        %h1#top_pagetitle= link_to t("page_title"), root_path
    %section.top-bar-section
      %ul.left
        %li.has-form
          = form_tag search_path, :method => 'get' do
            .row.collapse
              .small-9.columns
                = text_field_tag :query, params[:query]
              .small-3.columns    
                = submit_tag t("search_button"), :name => nil, class: "button radius expand"
      %ul.right    
        %li
          - if @feed
            - if current_user.trustworthiness[0] > TRUST_STAGE[@feed.stage]
              = link_to trustworthiness_in_precent, explain_trust_path,  class: "user_trustworthiness trusted", id: "jr_trust_link"
            - else
              = link_to trustworthiness_in_precent, explain_trust_path,  class: "user_trustworthiness not_trusted", id: "jr_trust_link"
          - else
            = link_to trustworthiness_in_precent, explain_trust_path,  class: "user_trustworthiness", id: "jr_trust_link"
 

        %li.has-dropdown
          %a{href: "#"}= t("feeds_drop")
          %ul.dropdown    
            %li= link_to t("all_feeds_list"), feeds_path()          
            %li= link_to t("contributed_feed_list"), all_feeds_of_type_path(index_type: "contributed")
            %li= link_to t("active_feed_list"), all_feeds_of_type_path(index_type: "active")
            %li= link_to t("free_feed_list"), all_feeds_of_type_path(index_type: "free")
          
          
        - if user_signed_in?

          %li.has-dropdown
            %a#jr_profile_link{href: "#"}= current_user.name
            %ul.dropdown
              %li= link_to t("profile_link"), user_path(current_user.id) 
              %li= link_to t('edit_account_link'), edit_user_registration_path
              %li= link_to t('logout_link'), destroy_user_session_path, :method=>'delete'
              

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : t('page_title')
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'freed.li'}"}
    = stylesheet_link_tag "application"
    -# Foundation 5 won't work with Rails Turbolinks
    -# Modernizr is required for Zurb Foundation
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags
  %body
    = render "layouts/top_bar"
    .off-canvas-wrap
      .inner-wrap
        = render "layouts/off_canvas", feed: @feed
        %section{role: "main"}
          .row
            .small-9.small-centered.columns.top-margin
              = render 'layouts/messages'
          
          = yield
          
          = render "layouts/footer"
          
    -# Foundation 5 won't work when application.js is included in HEAD
    = javascript_include_tag "application"
    
    - if current_user # checks if the user is logged in for the first time on this computer
      - unless cookies["no_joyride_for_" + (current_user.id * 9 - 6).to_s] == "true"
        - cookies["no_joyride_for_" + (current_user.id * 9 - 6).to_s] = "true"  # set after first display to not annoy
        :javascript
          $(function() {
            $(document).foundation('joyride', 'start');
          });

app/views/layouts/home.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : t('page_title')
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Wispper'}"}
    = stylesheet_link_tag "application"
    -# Foundation 5 won't work with Rails Turbolinks
    -# Modernizr is required for Zurb Foundation
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags
  %body
    .row
      .small-offset-8.small-4.medium-offset-10.medium-2.columns.top-margin
        = form_tag(root_path, method: :get) do
          = select_tag('lang_change', options_from_collection_for_select(LANGUAGES_HASH, :first, :last, I18n.locale))
    
    .top-margin= yield
  
  -# Foundation 5 won't work when application.js is included in HEAD
  = javascript_include_tag "application"